server:
  port: 8799
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://loca*****:****"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: commandeModule
          uri: lb://microservice-commandes
          predicates:
            - Path=/commandes/**

        - id: produitModule
          uri: lb://microservice-produits
          predicates:
            - Path=/produits/**

        - id: autorisationProduitModule
          uri: lb://microservice-produits
          predicates:
            - Path=/autorisation-produits/**

        - id: paiements
          uri: lb://microservice-paiements
          predicates:
            - Path=/paiements/**




eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8802/eureka/}