server:
  port: 8762
spring:
  datasource:
    #url: jdbc:oracle:thin:@oracle_xe:1521/XEPDB1
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: none
      show-sql: true
    #liquibase:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    #change-log: db/changelog/db.changelog-master.xml


feign:
  client:
    microservice-produits:
      name: microservice-produits
      url: http://localhost:8761

params:
  pagination:
    sizeDefault: 10
    pageDefault: 0