server:
  port: 8761
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #url: jdbc:oracle:thin:@oracle_xe:1521/XEPDB1
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: none
    #liquibase:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    #change-log: db/changelog/db.changelog-master.xm
