server:
  port: 8782

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false



feign:
  client:
    microservice-produits:
      name: microservice-produits
      url: http://localhost:8781

params:
  pagination:
    sizeDefault: 10
    pageDefault: 0