server:
  port: 8781
# Configurations H2
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

#conf eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8802/eureka/